CREATE TABLE COMPORTE (
  Programme VARCHAR2 (128),
  idScore NUMBER,
  CONSTRAINT COMPORTE_PK06 PRIMARY KEY (Programme, idScore)
);

CREATE TABLE DEPEND_DE (
  idTache_Fille NUMBER,
  idTache_Mere NUMBER,
  CONSTRAINT DEPEND_DE_PK01 PRIMARY KEY (idTache_Fille, idTache_Mere),
  CONSTRAINT DEPEND_DE_CK01 CHECK (idTache_Fille != idTache_Mere)
);

CREATE TABLE EST_ASSIGNE (
  idUtilisateur NUMBER,
  idTache NUMBER,
  CONSTRAINT EST_ASSIGNE_PK02 PRIMARY KEY (idUtilisateur, idTache)
);

CREATE TABLE LISTE (
  idListe NUMBER CONSTRAINT LISTE_PK03 PRIMARY KEY,
  Nom_Projet VARCHAR2 (128) CONSTRAINT LISTE_NN01 NOT NULL,
  idUtilisateur NUMBER CONSTRAINT LISTE_NN02 NOT NULL,
  CONSTRAINT LISTE_UQ01 UNIQUE (Nom_Projet, idUtilisateur)
);

CREATE TABLE PERIODICITE (
  idPeriodicite NUMBER CONSTRAINT PERIODICITE_PK07 PRIMARY KEY,
  Date_Debut DATE,
  Date_Fin DATE,
  Intervalle INTERVAL DAY TO SECOND,
  CONSTRAINT PERIODICITE_CK04 CHECK (
    (
      Date_Debut IS NULL
      AND Intervalle IS NULL
    )
    OR (
      Date_Debut IS NOT NULL
      AND Intervalle IS NOT NULL
    )
  ),
  CONSTRAINT PERIODICITE_CK05 CHECK (
    Date_Fin IS NULL
    OR (
      Date_Debut IS NOT NULL
      AND Intervalle IS NOT NULL
    )
  )
);

CREATE TABLE SCORE (
  idScore NUMBER CONSTRAINT SCORE_PK08 PRIMARY KEY,
  Points NUMBER (3) CONSTRAINT SCORE_NN12 NOT NULL,
  Categorie VARCHAR2 (128) CONSTRAINT SCORE_NN13 NOT NULL,
  CONSTRAINT SCORE_CK07 CHECK (Points >= 0)
);

CREATE TABLE TACHE (idTache NUMBER CONSTRAINT TACHE_PK04 PRIMARY KEY);

CREATE TABLE TACHE_ACTUELLE (
  idTache NUMBER CONSTRAINT TACHE_ACTUELLE_PK04 PRIMARY KEY,
  Titre VARCHAR2 (128) CONSTRAINT TACHE_ACTUELLE_NN04 NOT NULL,
  Priorite NUMBER (1),
  Categorie VARCHAR2 (128) CONSTRAINT TACHE_ACTUELLE_NN11 NOT NULL,
  Lien VARCHAR2 (256),
  Description VARCHAR2 (1024),
  Date_Echeance DATE,
  Statut NUMBER (1) CONSTRAINT TACHE_ACTUELLE_NN05 NOT NULL,
  idPeriodicite NUMBER,
  Date_Realisation DATE,
  idListe NUMBER,
  idUtilisateur NUMBER CONSTRAINT TACHE_ACTUELLE_NN03 NOT NULL,
  CONSTRAINT TACHE_ACTUELLE_IM01 CHECK (
    Statut = 0
    AND Date_Realisation IS NULL
  )
);

CREATE TABLE TACHE_PASSEE (
  idTache NUMBER CONSTRAINT TACHE_PASSEE_PK04 PRIMARY KEY,
  Titre VARCHAR2 (128) CONSTRAINT TACHE_PASSEE_NN04 NOT NULL,
  Priorite NUMBER (1),
  Categorie VARCHAR2 (128) CONSTRAINT TACHE_PASSEE_NN11 NOT NULL,
  Lien VARCHAR2 (256),
  Description VARCHAR2 (1024),
  Date_Echeance DATE,
  Statut NUMBER (1) CONSTRAINT TACHE_PASSEE_NN05 NOT NULL,
  idPeriodicite NUMBER,
  Date_Realisation DATE,
  idListe NUMBER,
  idUtilisateur NUMBER CONSTRAINT TACHE_PASSEE_NN03 NOT NULL,
  CONSTRAINT TACHE_PASSEE_IM02 CHECK (
    Statut = 0
    OR Statut = 1
  ),
  CONSTRAINT TACHE_PASSEE_CK02 CHECK (
    (
      Statut = 1
      AND Date_Realisation IS NOT NULL
    )
    OR (
      Statut = 0
      AND Date_Realisation IS NULL
      AND Date_Echeance IS NOT NULL
    )
  ),
  CONSTRAINT TACHE_PASSEE_CK03 CHECK (
    Date_Realisation IS NULL
    OR Date_Echeance IS NULL
    OR Date_Realisation <= Date_Echeance
  )
);

CREATE TABLE UTILISATEUR (
  idUtilisateur NUMBER CONSTRAINT UTILISATEUR_PK05 PRIMARY KEY,
  Nom VARCHAR2 (128) CONSTRAINT UTILISATEUR_NN06 NOT NULL,
  Prenom VARCHAR2 (128) CONSTRAINT UTILISATEUR_NN07 NOT NULL,
  Adresse VARCHAR2 (256),
  Date_Naissance DATE,
  Date_Inscription DATE CONSTRAINT UTILISATEUR_NN08 NOT NULL,
  Login VARCHAR2 (10) CONSTRAINT UTILISATEUR_UQ02_NN09 UNIQUE NOT NULL,
  Mot_de_passe VARCHAR2 (128) CONSTRAINT UTILISATEUR_NN10 NOT NULL,
  Score NUMBER,
  Programme VARCHAR2 (128)
);

CREATE
OR REPLACE VIEW TACHES AS
SELECT
  *
FROM
  TACHE_ACTUELLE
UNION ALL
SELECT
  *
FROM
  TACHE_PASSEE;

ALTER TABLE COMPORTE ADD CONSTRAINT COMPORTE_FK06 FOREIGN KEY (idScore) REFERENCES SCORE (idScore);

ALTER TABLE DEPEND_DE ADD CONSTRAINT DEPEND_DE_FK08 FOREIGN KEY (idTache_Fille) REFERENCES TACHE (idTache) ON DELETE CASCADE;

ALTER TABLE DEPEND_DE ADD CONSTRAINT DEPEND_DE_FK09 FOREIGN KEY (idTache_Mere) REFERENCES TACHE (idTache) ON DELETE CASCADE;

ALTER TABLE EST_ASSIGNE ADD CONSTRAINT EST_ASSIGNE_FK01 FOREIGN KEY (idUtilisateur) REFERENCES UTILISATEUR (idUtilisateur) ON DELETE CASCADE;

ALTER TABLE EST_ASSIGNE ADD CONSTRAINT EST_ASSIGNE_FK10 FOREIGN KEY (idTache) REFERENCES TACHE (idTache) ON DELETE CASCADE;

ALTER TABLE LISTE ADD CONSTRAINT LISTE_FK03 FOREIGN KEY (idUtilisateur) REFERENCES UTILISATEUR (idUtilisateur) ON DELETE CASCADE;

ALTER TABLE TACHE_ACTUELLE ADD CONSTRAINT TACHE_ACTUELLE_FK11 FOREIGN KEY (idTache) REFERENCES TACHE (idTache) ON DELETE CASCADE;

ALTER TABLE TACHE_ACTUELLE ADD CONSTRAINT TACHE_ACTUELLE_FK05 FOREIGN KEY (idListe) REFERENCES LISTE (idListe) ON DELETE SET NULL;

ALTER TABLE TACHE_ACTUELLE ADD CONSTRAINT TACHE_ACTUELLE_FK04 FOREIGN KEY (idUtilisateur) REFERENCES UTILISATEUR (idUtilisateur) ON DELETE CASCADE;

ALTER TABLE TACHE_ACTUELLE ADD CONSTRAINT TACHE_ACTUELLE_FK07 FOREIGN KEY (idPeriodicite) REFERENCES PERIODICITE (idPeriodicite);

ALTER TABLE TACHE_PASSEE ADD CONSTRAINT TACHE_PASSEE_FK11 FOREIGN KEY (idTache) REFERENCES TACHE (idTache) ON DELETE CASCADE;

ALTER TABLE TACHE_PASSEE ADD CONSTRAINT TACHE_PASSEE_FK05 FOREIGN KEY (idListe) REFERENCES LISTE (idListe) ON DELETE SET NULL;

ALTER TABLE TACHE_PASSEE ADD CONSTRAINT TACHE_PASSEE_FK04 FOREIGN KEY (idUtilisateur) REFERENCES UTILISATEUR (idUtilisateur) ON DELETE CASCADE;

ALTER TABLE TACHE_PASSEE ADD CONSTRAINT TACHE_PASSEE_FK07 FOREIGN KEY (idPeriodicite) REFERENCES PERIODICITE (idPeriodicite);
