-- DROP VIEW TACHE;
-- DROP TABLE DEPENDRE CASCADE CONSTRAINTS;
-- DROP TABLE ETRE_ASSIGNE CASCADE CONSTRAINTS;
-- DROP TABLE LISTE CASCADE CONSTRAINTS;
-- DROP TABLE TACHE_ACTUELLE CASCADE CONSTRAINTS;
-- DROP TABLE TACHE_PASSEE CASCADE CONSTRAINTS;
-- DROP TABLE UTILISATEUR CASCADE CONSTRAINTS;
-- DROP TYPE PROGRAMME;
BEGIN EXECUTE IMMEDIATE 'DROP VIEW TACHE';

EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE;

END IF;

END;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DEPENDRE CASCADE CONSTRAINTS';

EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE;

END IF;

END;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE ETRE_ASSIGNE CASCADE CONSTRAINTS';

EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE;

END IF;

END;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE LISTE CASCADE CONSTRAINTS';

EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE;

END IF;

END;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE TACHE_ACTUELLE CASCADE CONSTRAINTS';

EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE;

END IF;

END;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE TACHE_PASSEE CASCADE CONSTRAINTS';

EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE;

END IF;

END;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE UTILISATEUR CASCADE CONSTRAINTS';

EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE;

END IF;

END;

BEGIN EXECUTE IMMEDIATE 'DROP TYPE PROGRAMME';

EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE;

END IF;

END;
