-- DROP VIEW TACHES;
-- DROP TABLE COMPORTE CASCADE CONSTRAINTS;
-- DROP TABLE DEPEND_DE CASCADE CONSTRAINTS;
-- DROP TABLE EST_ASSIGNE CASCADE CONSTRAINTS;
-- DROP TABLE LISTE CASCADE CONSTRAINTS;
-- DROP TABLE PERIODICITE CASCADE CONSTRAINTS;
-- DROP TABLE SCORE CASCADE CONSTRAINTS;
-- DROP TABLE TACHE CASCADE CONSTRAINTS;
-- DROP TABLE TACHE_ACTUELLE CASCADE CONSTRAINTS;
-- DROP TABLE TACHE_PASSEE CASCADE CONSTRAINTS;
-- DROP TABLE UTILISATEUR CASCADE CONSTRAINTS;
BEGIN EXECUTE IMMEDIATE 'DROP VIEW TACHES';

EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE;

END IF;

END;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE COMPORTE CASCADE CONSTRAINTS';

EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE;

END IF;

END;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE DEPEND_DE CASCADE CONSTRAINTS';

EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE;

END IF;

END;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE EST_ASSIGNE CASCADE CONSTRAINTS';

EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE;

END IF;

END;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE LISTE CASCADE CONSTRAINTS';

EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE;

END IF;

END;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE PERIODICITE CASCADE CONSTRAINTS';

EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE;

END IF;

END;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE SCORE CASCADE CONSTRAINTS';

EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE;

END IF;

END;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE TACHE CASCADE CONSTRAINTS';

EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE;

END IF;

END;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE TACHE_ACTUELLE CASCADE CONSTRAINTS';

EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE;

END IF;

END;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE TACHE_PASSEE CASCADE CONSTRAINTS';

EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE;

END IF;

END;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE UTILISATEUR CASCADE CONSTRAINTS';

EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE;

END IF;

END;
